[package]
name = "server"
version = "0.1.0"
edition = "2024"


[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
dotenvy.workspace = true
oauth-axum = "0.1.4"
tower = "0.5.2"
axum = "0.8.4"
tower-http = { version = "0.6.6", features = ["trace"] }
